import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import HeroSection from '../components/HeroSection';
import SafesSection from '../components/SafesSection';
import Footer from '../components/Footer';
import MaintenancePage from '../components/MaintenancePage'; // Import the MaintenancePage

const Home: NextPage = () => {
  const date = new Date(); // Current date and time
  const estTime = new Date(date.toLocaleString("en-US", { timeZone: "America/New_York" })); // Convert to New York time
  const dayOfWeek = estTime.getDay(); // Sunday - 0, Monday - 1, ..., Saturday - 6
  const hour = estTime.getHours(); // Get the hour in 24-hour format

  // Define operating hours
  const isOpen = (
    dayOfWeek !== 0 && // Closed on Sundays
    hour >= 9 && // Opening time
    hour < 17 // Closing time (5 PM is 17 in 24-hour format)
  );

  if (!isOpen) {
    return <MaintenancePage />; // Render the Maintenance Page outside operating hours
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Voodoo Token Safe</title>
        <meta content="Generated by create-next-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Navbar logoSrc="/logo.png" />
      <div className="flex-grow">
        <HeroSection />
        <SafesSection />
      </div>

      <Footer className="mt-auto" />
    </div>
  );
};

export default Home;
